version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mongo
            host: ${DB_HOST}
            user: ${DB_USER} 
            password: ${DB_PASSWORD}
            uri: >-
              mongodb+srv://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/test?retryWrites=true&w=majority